require("blum.plugins")
require("blum.options")
require("blum.colors")

require("blum.cfg_treesitter")
require("blum.cfg_telescope")
require("blum.cfg_cmp")
require("blum.cfg_lsp")
require("blum.cfg_rust")
require("blum.cfg_harpoon")
