vim.g.mapleader = ","
vim.g.localmapleader = "\\"

vim.opt.autowrite = true
vim.opt.background = "dark"
vim.opt.cmdheight = 1
vim.opt.colorcolumn = "101"
vim.opt.complete = { ".", "w", "b", "u", "i", "d", "t" }
vim.opt.completeopt = { "menuone", "noselect" }
vim.opt.confirm = true
vim.opt.cursorline = true
vim.opt.encoding = "utf-8"
vim.opt.expandtab = true
vim.opt.fileencoding = "utf-8"
vim.opt.fileencodings = { "utf-8" }
vim.opt.fileformat = "unix"
vim.opt.grepprg = "rg --vimgrep"
vim.opt.hidden = true
vim.opt.incsearch = true
vim.opt.ignorecase = true
vim.opt.lazyredraw = true
vim.opt.list = true
vim.opt.listchars = { tab = "» " , trail = "·" , eol = "¬" }
vim.opt.mouse = "a"
vim.opt.backup = false
vim.opt.hlsearch = false
vim.opt.showmode = false
vim.opt.swapfile = false
vim.opt.wrap = false
vim.opt.writebackup = false
vim.opt.number = true
vim.opt.pastetoggle = "<F2>"
vim.opt.relativenumber = true
vim.opt.scrolloff = 4
vim.opt.secure = true
vim.opt.shiftround = true
vim.opt.shiftwidth = 4
vim.opt.shortmess:append("c")
vim.opt.showcmd = true
vim.opt.showmatch = true
vim.opt.signcolumn = "yes"
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.softtabstop = 4
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.termguicolors = true
vim.opt.textwidth = 0
vim.opt.undofile = true
vim.opt.updatetime = 300
vim.opt.wildmenu = true
vim.opt.wildmode = "list:longest"
